[package]
name = "ligeia"
version = "0.1.0"
authors = ["Alex Hoar <thealexhoar@gmail.com>"]

[dependencies]
bit-set = "0.4.0"
liquidfun = { path = "liquidfun-rust" }
serde = "1.0.37"
serde_json = "1.0.13"
sfml = { path = "rust-sfml"}
specs = "0.10.0"
specs-derive = "0.1.0"