[package]
name = "ligeia-utils"
version = "0.1.0"
authors = ["Alex Hoar <thealexhoar@gmail.com>"]

[dependencies]
image = "0.19.0"
num-traits = "0.2"
sdl2 = "0.31.0"
serde = "1.0.37"
serde_json = "1.0.13"
